[tool.poetry]
authors = [
    "Georgios Konstantopoulos <me@gakonst.com>",
    "Nikolas Papaioannou <n0k0@hacky.software>",
    "Brock Smedley <brock@flashbots.net>",
]
description = ""
name = "flashbots"
readme = "README.md"
version = "3.0.0"

[tool.poetry.dependencies]
python = "^3.9"
web3 = "^7.0.0"
urllib3 = "<2.0"
websockets = "^13.0.0" #lock to 13.x to avoid warnings because Web3.py v7.11.0 pulls in websockets.legacy
eth-account = "^0.13.7"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0.0"
ruff = "^0.5.4"
pytest-recording = "^0.11.0"
vcrpy = "^4.1.1"

[tool.ruff]
target-version = "py312"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
